_G.autotap = true
while _G.autotap == true do
	-- Script generated by SimpleSpy - credits to shezan

local args = {
    [1] = "collectOrb",
    [2] = "Gem",
    [3] = "City"
}

game:GetService("ReplicatedStorage").rEvents.orbEvent:FireServer(unpack(args))
	
	wait()
end
-- If u wanna turn off use execute 
-- _G.autotap = false
